<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TagsTableSeeder extends Seeder
{
    public function run(): void
    {
        $tags = [
            ['tag_en' => 'Politics', 'tag_bn' => 'রাজনীতি'],
            ['tag_en' => 'Elections', 'tag_bn' => 'নির্বাচন'],
            ['tag_en' => 'Economy', 'tag_bn' => 'অর্থনীতি'],
            ['tag_en' => 'Inflation', 'tag_bn' => 'মুদ্রাস্ফীতি'],
            ['tag_en' => 'Stock Market', 'tag_bn' => 'শেয়ার বাজার'],
            ['tag_en' => 'Business', 'tag_bn' => 'ব্যবসা'],
            ['tag_en' => 'Sports', 'tag_bn' => 'খেলাধুলা'],
            ['tag_en' => 'Football', 'tag_bn' => 'ফুটবল'],
            ['tag_en' => 'Cricket', 'tag_bn' => 'ক্রিকেট'],
            ['tag_en' => 'Tennis', 'tag_bn' => 'টেনিস'],
            ['tag_en' => 'Technology', 'tag_bn' => 'প্রযুক্তি'],
            ['tag_en' => 'Gadgets', 'tag_bn' => 'গ্যাজেট'],
            ['tag_en' => 'Education', 'tag_bn' => 'শিক্ষা'],
            ['tag_en' => 'Schools', 'tag_bn' => 'বিদ্যালয়'],
            ['tag_en' => 'Colleges', 'tag_bn' => 'কলেজ'],
            ['tag_en' => 'Universities', 'tag_bn' => 'বিশ্ববিদ্যালয়'],
            ['tag_en' => 'Health', 'tag_bn' => 'স্বাস্থ্য'],
            ['tag_en' => 'Medicine', 'tag_bn' => 'ঔষধ'],
            ['tag_en' => 'Nutrition', 'tag_bn' => 'পুষ্টি'],
            ['tag_en' => 'Fitness', 'tag_bn' => 'ফিটনেস'],
            ['tag_en' => 'Environment', 'tag_bn' => 'পরিবেশ'],
            ['tag_en' => 'Climate Change', 'tag_bn' => 'জলবায়ু পরিবর্তন'],
            ['tag_en' => 'Pollution', 'tag_bn' => 'দূষণ'],
            ['tag_en' => 'Natural Disasters', 'tag_bn' => 'প্রাকৃতিক দুর্যোগ'],
            ['tag_en' => 'International', 'tag_bn' => 'আন্তর্জাতিক'],
            ['tag_en' => 'World News', 'tag_bn' => 'বিশ্ব সংবাদ'],
            ['tag_en' => 'UN', 'tag_bn' => 'জাতিসংঘ'],
            ['tag_en' => 'Trade', 'tag_bn' => 'বাণিজ্য'],
            ['tag_en' => 'Finance', 'tag_bn' => 'আর্থিক'],
            ['tag_en' => 'Crime', 'tag_bn' => 'অপরাধ'],
            ['tag_en' => 'Law', 'tag_bn' => 'আইন'],
            ['tag_en' => 'Police', 'tag_bn' => 'পুলিশ'],
            ['tag_en' => 'Traffic', 'tag_bn' => 'যানজট'],
            ['tag_en' => 'Culture', 'tag_bn' => 'সংস্কৃতি'],
            ['tag_en' => 'Music', 'tag_bn' => 'সঙ্গীত'],
            ['tag_en' => 'Movies', 'tag_bn' => 'সিনেমা'],
            ['tag_en' => 'Art', 'tag_bn' => 'চিত্রকলার'],
            ['tag_en' => 'Books', 'tag_bn' => 'বই'],
            ['tag_en' => 'Religion', 'tag_bn' => 'ধর্ম'],
            ['tag_en' => 'Festival', 'tag_bn' => 'উৎসব'],
            ['tag_en' => 'Travel', 'tag_bn' => 'ভ্রমণ'],
            ['tag_en' => 'Tourism', 'tag_bn' => 'পর্যটন'],
            ['tag_en' => 'Food', 'tag_bn' => 'খাবার'],
            ['tag_en' => 'Recipes', 'tag_bn' => 'রেসিপি'],
            ['tag_en' => 'Fashion', 'tag_bn' => 'ফ্যাশন'],
            ['tag_en' => 'Beauty', 'tag_bn' => 'সৌন্দর্য'],
            ['tag_en' => 'Lifestyle', 'tag_bn' => 'জীবনধারা'],
            ['tag_en' => 'Opinion', 'tag_bn' => 'মতামত'],
            ['tag_en' => 'Editorial', 'tag_bn' => 'সম্পাদকীয়'],
            ['tag_en' => 'Science', 'tag_bn' => 'বিজ্ঞান'],
            ['tag_en' => 'Research', 'tag_bn' => 'গবেষণা'],
            ['tag_en' => 'Space', 'tag_bn' => 'মহাকাশ'],
            ['tag_en' => 'Agriculture', 'tag_bn' => 'কৃষি'],
            ['tag_en' => 'Farming', 'tag_bn' => 'চাষাবাদ'],
            ['tag_en' => 'Fishing', 'tag_bn' => 'মাছধরা'],
            ['tag_en' => 'Economics', 'tag_bn' => 'অর্থনীতি বিষয়ক'],
            ['tag_en' => 'Banking', 'tag_bn' => 'ব্যাংকিং'],
            ['tag_en' => 'Startups', 'tag_bn' => 'স্টার্টআপ'],
            ['tag_en' => 'Jobs', 'tag_bn' => 'চাকরি'],
            ['tag_en' => 'Employment', 'tag_bn' => 'কর্মসংস্থান'],
            ['tag_en' => 'Real Estate', 'tag_bn' => 'আবাসন'],
            ['tag_en' => 'Housing', 'tag_bn' => 'বাসস্থান'],
            ['tag_en' => 'Traffic Accidents', 'tag_bn' => 'ট্রাফিক দুর্ঘটনা'],
            ['tag_en' => 'Weather', 'tag_bn' => 'আবহাওয়া'],
            ['tag_en' => 'Flood', 'tag_bn' => 'বন্যা'],
            ['tag_en' => 'Cyclone', 'tag_bn' => 'চক্রবাত'],
            ['tag_en' => 'Fire', 'tag_bn' => 'আগুন'],
            ['tag_en' => 'Corruption', 'tag_bn' => 'দুর্নীতি'],
            ['tag_en' => 'NGO', 'tag_bn' => 'এনজিও'],
            ['tag_en' => 'Government', 'tag_bn' => 'সরকার'],
            ['tag_en' => 'Policy', 'tag_bn' => 'নীতি'],
            ['tag_en' => 'Budget', 'tag_bn' => 'বাজেট'],
            ['tag_en' => 'Taxes', 'tag_bn' => 'কর'],
            ['tag_en' => 'Transportation', 'tag_bn' => 'পরিবহন'],
            ['tag_en' => 'Railway', 'tag_bn' => 'রেলওয়ে'],
            ['tag_en' => 'Airport', 'tag_bn' => 'বিমানবন্দর'],
            ['tag_en' => 'Port', 'tag_bn' => 'বন্দর'],
            ['tag_en' => 'Maritime', 'tag_bn' => 'সমুদ্র সংক্রান্ত'],
            ['tag_en' => 'Police Brutality', 'tag_bn' => 'পুলিশের সহিংসতা'],
            ['tag_en' => 'Human Rights', 'tag_bn' => 'মানবাধিকার'],
            ['tag_en' => 'Refugee', 'tag_bn' => 'শরণার্থী'],
            ['tag_en' => 'Migration', 'tag_bn' => 'প্রবাসী'],
            ['tag_en' => 'Education Policy', 'tag_bn' => 'শিক্ষা নীতি'],
            ['tag_en' => 'Healthcare', 'tag_bn' => 'স্বাস্থ্যসেবা'],
            ['tag_en' => 'Vaccination', 'tag_bn' => 'টিকা'],
            ['tag_en' => 'COVID-19', 'tag_bn' => 'কোভিড-১৯'],
            ['tag_en' => 'Technology News', 'tag_bn' => 'প্রযুক্তি সংবাদ'],
            ['tag_en' => 'AI', 'tag_bn' => 'কৃত্রিম বুদ্ধিমত্তা'],
            ['tag_en' => 'Gadgets Review', 'tag_bn' => 'গ্যাজেট পর্যালোচনা'],
            ['tag_en' => 'Internet', 'tag_bn' => 'ইন্টারনেট'],
            ['tag_en' => 'Social Media', 'tag_bn' => 'সোশ্যাল মিডিয়া'],
            ['tag_en' => 'Facebook', 'tag_bn' => 'ফেসবুক'],
            ['tag_en' => 'Twitter', 'tag_bn' => 'টুইটার'],
            ['tag_en' => 'Instagram', 'tag_bn' => 'ইনস্টাগ্রাম'],
            ['tag_en' => 'YouTube', 'tag_bn' => 'ইউটিউব'],
            ['tag_en' => 'TikTok', 'tag_bn' => 'টিকটক'],
            ['tag_en' => 'Movies Review', 'tag_bn' => 'সিনেমা পর্যালোচনা'],
            ['tag_en' => 'Drama', 'tag_bn' => 'নাটক'],
            ['tag_en' => 'Celebrity', 'tag_bn' => 'সেলিব্রিটি'],
            ['tag_en' => 'Fashion Show', 'tag_bn' => 'ফ্যাশন শো'],
            ['tag_en' => 'Beauty Tips', 'tag_bn' => 'সৌন্দর্য টিপস'],
            ['tag_en' => 'Travel Guide', 'tag_bn' => 'ভ্রমণ নির্দেশিকা'],
            ['tag_en' => 'Tourist Spot', 'tag_bn' => 'পর্যটন স্থান'],
            ['tag_en' => 'Food Review', 'tag_bn' => 'খাবার পর্যালোচনা'],
            ['tag_en' => 'Recipe', 'tag_bn' => 'রেসিপি'],
            ['tag_en' => 'Festival', 'tag_bn' => 'উৎসব'],
            ['tag_en' => 'Local News', 'tag_bn' => 'স্থানীয় সংবাদ'],
            ['tag_en' => 'Bangladesh', 'tag_bn' => 'বাংলাদেশ'],
            ['tag_en' => 'Dhaka', 'tag_bn' => 'ঢাকা'],
            ['tag_en' => 'Chittagong', 'tag_bn' => 'চট্টগ্রাম'],
            ['tag_en' => 'Rangpur', 'tag_bn' => 'রংপুর'],
            ['tag_en' => 'Sylhet', 'tag_bn' => 'সিলেট'],
            ['tag_en' => 'Khulna', 'tag_bn' => 'খুলনা'],
            ['tag_en' => 'Barishal', 'tag_bn' => 'বরিশাল'],
            ['tag_en' => 'Mymensingh', 'tag_bn' => 'ময়মনসিংহ'],
            ['tag_en' => 'Comilla', 'tag_bn' => 'কুমিল্লা'],
        ];

        // insert all at once
        $allTags = array_map(function ($tag) {
            return array_merge($tag, [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }, $tags);

        DB::table('tags')->insert($allTags);
    }
}
